apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.appname }}
  name: {{ .Values.appname }}
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
    - port: 4111
      protocol: TCP
      targetPort: {{ default .Values.service.Port .Values.service.targetPort }}
  selector:
    app: {{ .Values.appname }}
  type: ClusterIP